### ISSUE TITLE
don't work in production build

### ISSUE THREAD

**Issue by pavellzubkov** [ncform/ncform#53]
I make  [fork](https://github.com/pavellzubkov/vue-admin-fork) from  [vue-element-admin](https://github.com/PanJiaChen/vue-element-admin) and then add exampte from [ncform-demo](https://github.com/daniel-dx/ncform-demo) on dashboard. 
When run "npm run dev" ncform work fine, but when run "npm run build" and deploy it doesn't work.
May be needs some special settings for webpack? I can't see some errors...

**Comment by daniel-dx** [comment]
Got it, i will test the case as soon as possible

**Comment by daniel-dx** [comment]
I tested the production mode of the project created by vue-cli （webpack v4.28.4） is OK.

But the production mode of vue-element-admin（webpack 4.16.5） is problematic.

I guess it is a problem with webpack  or some loaders， finally i found the root cause.

The following is the source code fragment of the ncform-common package.
```
widget:
                        t.widget ||
                        (function(e) {
                          var t = 'input';
                          switch (e) {
                            case 'boolean':
                              t = 'radio';
                              break;
                            case 'object':
                              t = 'object';
                              break;
                            case 'array':
                              t = 'array';
                              break;
                            default:
                              t = 'input';
                          }
                          return t;
                        })(r),
```
It is compiled into the following code in the vue-element-admin production mode.

```
widget: t.widget || "input",
```

This is the root cause. 

So the solution is to explicitly declare the widget as shown below

```
      {
        type: "object",
        properties: {
          name: {
            type: "string"
          },
          gender: {
            type: "boolean",
            ui: {
              widget: "radio"
            }
          }
        },
        ui: {
          widget: "object",
          widgetConfig: {
            layout: "h"
          }
        }
      }
```

**Comment by daniel-dx** [comment]
The safest solution is to upgrade webpack and related loaders, but I have no luck to do it successfully for vue-element-admin.

**Comment by pavellzubkov** [comment]
great!
